# Generated by Django 5.1.2 on 2024-11-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdiary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookdiaryForm',
            new_name='Bookdiary',
        ),
    ]
